# Generated by Django 4.2 on 2023-07-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(default='', upload_to='uploads/products/'),
        ),
    ]
