# Generated by Django 4.2 on 2023-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(default=0),
        ),
    ]
